### ISSUE TITLE
GES: missing dependency ?

### ISSUE THREAD

**Issue by maoschanz** [bilelmoussaoui/Audio-Cutter#11]
i wanted to build it (with GNOME Builder) and then

```
Application started at 18:51:17
Traceback (most recent call last):
  File "/app/bin/audio-cutter", line 29, in <module>
    require_version("GES", "1.0")
  File "/usr/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GES not available
Application exited
```

no idea why, it worked before

**Comment by bilelmoussaoui** [comment]
If it worked before, it should work now :p Have you tried to build and run it using flatpak-builder?

**Comment by maoschanz** [comment]
oh no it's recompiling everything :'(

**Comment by bilelmoussaoui** [comment]
You want to hack on it or just try it? If it's just to try it, there isn't much to try now :p

**Comment by maoschanz** [comment]
i'm trying to add things for translations

**Comment by bilelmoussaoui** [comment]
To be honest, just compile it using meson/ninja ;) the flatpak should make things easier, but I will need to reduce what should be compiled with flatpak. For now, it does work but it's not perfect
